name: End-to-end tests
on:
  schedule:
    - cron: "44 * * * *"
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main, feature/**, hotfix/**]
jobs:
  test:
    name: Run end-to-end tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install age
        run: sudo apt-get install -y age
      - name: Access secret key
        run: echo "${{ secrets.AGE_SECRET_KEY }}" > age-secret-key.txt
      - name: Decrypt hidden test configs
        run: age --decrypt -i age-secret-key.txt tests/hidden/hidden.enc.yml > tests/hidden/hidden.yml
      - name: Mask secrets from hidden test config
        run: bash script/add_masks.sh
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install dependencies
        run: pnpm install
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps
      - name: Setup environment variables
        run: mv production.env .env
      - name: Run Playwright tests
        run: pnpm run test
